- hosts: raspberries
  remote_user: pi
  tasks:
  - name: update APT cache if the last one is more than 3600 seconds old
    become: true
    apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: Install Python 2,3 and its GPIOs
    become: true
    apt:
      name:
      - python3
      - python
      - python3-rpi.gpio
      - python-rpi.gpio
      state: installed
  - name: Install Joe Editor
    become: true
    apt: pkg=joe state=installed
